### ISSUE TITLE
official binaries?

### ISSUE THREAD

**Issue by rusefillc** [corygrant/CANBoard_FW#1]
github has a feature to host official binaries any chance for any official binary?

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by corygrant** [comment]
That's a good idea, I'll see what I can do

**Comment by corygrant** [comment]
Hopefully I did that correctly! 
http://github.com/corygrant/CANBoard_FW/releases/tag/v1.0

**Comment by rusefillc** [comment]
looks great https://github.com/corygrant/CANBoard_FW/releases
