### ISSUE TITLE
Should freertos be pointing at official freertos?

### ISSUE THREAD

**Issue by rusefillc** [corygrant/CANBoard_FW#2]
I see https://github.com/corygrant/CANBoard_FW/tree/main/Middlewares/Third_Party/FreeRTOS should it be using https://github.com/freertos as a git submodule?

**Comment by corygrant** [comment]
I believe the version I'm using from the Cube firmware has been modified by ST.

**Comment by rusefillc** [comment]
Ohh

they probably have published it somewhere but whatever. Maybe one day someone knowing more about FreeRTOS would help :)

**Comment by corygrant** [comment]
No longer using freertos
