### ISSUE TITLE
three lines of documentation on tools used?

### ISSUE THREAD

**Issue by rusefillc** [corygrant/CANBoard_FW#3]
i see no Makefile :(

I see some Eclipse-based IDE any chance to spell out what IDEA this is? is that mxcube? any specific version known to open this project mxcube?

seeing that a lot of code was done two years ago can you mention which GCC is known to work for this source code? i know there are minor nasty differences between 9, 10, 11 and 12

**Comment by corygrant** [comment]
Updated the readme with my versions. 
I'm using CubeIDE, I'm not sure what some of those files are for.
