### ISSUE TITLE
CAN id ranges - no way to run two units on same network?

### ISSUE THREAD

**Issue by rusefillc** [corygrant/CANBoard_FW#5]
* Each devices uses four addresses BASE,BASE+1.. BASE+3
* jumpers allow four consecutive options

Those two together mean there is no way to configure for two units on same network?

https://github.com/corygrant/CANBoard_HW#jumpers

**Comment by corygrant** [comment]
Yes good catch. 
Perhaps jump by 10?

**Comment by rusefillc** [comment]
jump by 0x10 yes?

**Comment by corygrant** [comment]
I realized I never actually implemented the jumpers. Added an offset of 0x10 per jumper step.
