### ISSUE TITLE
command line compilation

### ISSUE THREAD

**Issue by rusefillc** [corygrant/CANBoard_FW#7]
Any chance to compile firmware from command line?

**Comment by rusefillc** [comment]
They say stm32cubeidec has command line option?

https://github.com/opelpanfan/car-dash-wide/issues/5#issuecomment-1448950778

**Comment by corygrant** [comment]
Yes I believe that is possible, but I've never used it. 
Or, things could move away from Cube. 
I use it because it's easy and I haven't had a chance to learn STM32 CLI. 
Are you familar with it?

**Comment by rusefillc** [comment]
I only use stm32 with ChibiOS not freertos but definitely with Makefile i.e. only CLI

https://developer.arm.com/downloads/-/gnu-rm is where we take the arm gcc port

**Comment by corygrant** [comment]
Using ChibiOS now
