### ISSUE TITLE
howto flash firmware

### ISSUE THREAD

**Issue by pknetworksolutions** [corygrant/CANBoard_FW#8]
Not really an issue, but do you have infos on hardware used, and the howto to flash the firmware?

**Comment by corygrant** [comment]
You'll need a TC2030 cable to flash the firmware. I use this one with a ST Link V3 Mini:
https://www.tag-connect.com/product/tc2030-ctx-nl-stdc14-for-use-with-stm32-processors-with-stlink-v3

https://www.st.com/en/development-tools/stlink-v3mini.html

If you want to leave the cable connected while debugging these hold the cable to the board 
https://www.tag-connect.com/product/tc2030-retaining-clip-board-3-pack

**Comment by pknetworksolutions** [comment]
Gotcha, I wasnt sure about the st link, which version. Already have the tag
connect

Le mar. 28 mars 2023, 20 h 16, Cory Grant ***@***.***> a
écrit :

**Comment by pknetworksolutions** [comment]
Last question, bin vs elf file, which one to use in which scenario?

**UPDATE** found the info, bin is the data properly, elf includes debugging content.
